version: '3.9' #2.1'
services:
  webservice:
    build: ./app
    ports:
      - "8080:8080"
      - "8001:5000"
    environment:
      - "FLASK_PORT=8080"

  # redis:
  #   image: redis:3.2
  #   ports:
  #     - "0:6379"